#############################################################################
## Assign container rights for managing spawn container
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  # to allow manage a deployment in APIGroup "apps"
  - apiGroups:
    - "apps"
    resources:
      - deployments
      - deployments/status
      - deployments/scale
    verbs: ["create", "get", "list", "delete", "patch"] # patch, get, list, create, delete
  # to allow manage a deployment in APIGroup "", coreapi
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - services
    verbs: ["create", "get", "list", "delete", "patch"] # patch, get, list, create, delete
  # to allow manage a mappings in cusrtom APIGroup "getambassador.io"
  - apiGroups:
    - "getambassador.io"
    resources:
      - mappings
    verbs: ["create", "delete", "patch", "list"] # patch, create, delete, list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aas-backend.serviceAccountName" . }}-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aas-backend.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aas-backend.serviceAccountName" . }}-role
  namespace: {{ .Release.Namespace }}
