ingress:
  enabled: false # Please use false if using Openshift.
  className: "nginx"
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m # Max upload size 10GB
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: appstore.ai
      paths:
        - path: /(.*)
          pathType: Prefix
          backend:
            service:
              name: aas-frontend
              port: 80

service:
  type: ClusterIP

env:
  VUE_APP_BACKEND_URL: https://aas-backend.<domain-name> # If using OpenShift, please use the Openshift route for back-end
  VUE_APP_KEYCLOAK_CLIENT_ID_ENV: ai-appstore-frontend
  VUE_APP_KEYCLOAK_URL_ENV: https://keycloak.<domain-name>
  VUE_APP_KEYCLOAK_REALM_ENV: CommonServices

image:
  repository: docker.io/<docker_username>/aas-frontend # Please use own repository link for front-end image.
  pullPolicy: Always
  tag: "1.2.0"
  
