env:
  PROD_FRONTEND_HOST: http://appstore.ai
  PROD_SECRET_KEY: 60bbf2dacae7ed30a5f79a31f2e1f0424dfbed678ea0b23c7c3374b3a67c1119
  PROD_ADMIN_SECRET_KEY: 60bbf2dacae7ed30a5f79a31f2e1f0424dfbed678ea0b23c7c3374b3a67c1119
  PROD_ALGORITHM: HS256
  PROD_MONGO_DSN: mongodb://aas-mongodb
  PROD_DB_NAME: appStoreProdDB
  PROD_MAX_UPLOAD_SIZE_GB: "10"
  PROD_MONGO_USERNAME: aasRootDBUser
  PROD_MONGO_PASSWORD: TempPassword1234
  PROD_IE_NAMESPACE: inference-engine
  CLEARML_WEB_HOST: https://app.clear.ml
  CLEARML_API_HOST: https://api.clear.ml
  CLEARML_FILES_HOST: https://files.clear.ml
  CLEARML_API_ACCESS_KEY: 5BGFOYCD786OFPFP3M9F
  CLEARML_API_SECRET_KEY: HHqILZP4YZqOeTKneHUEc4oG6VosVEfDtVQV2ySheRLFVq9aSn
environment: prod

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.allow-http: "true"
    # kubernetes.io/tls-acme: "true"
  hosts:
    # Note for local dev, set the following in the hostfile
    # 127.0.0.1 api.appstore.ai
    # 127.0.0.1 appstore.ai
    - host: "api.appstore.ai"
      paths:
        - path: /
          pathType: Prefix
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
