define: &uid 8888 # For openshift, pls use the UID within the project UID range.

image:
  repository: docker.io/emissaryingress/emissary
  tag: 3.4.0

agent:
  image:
    repository: docker.io/ambassador/ambassador-agent
    tag: 1.0.3

createDefaultListeners: true

security:
  podSecurityContext:
    runAsUser: *uid

service:
  type: LoadBalancer
  loadBalancerIP: appstore-model.<domain-name> # For Openshift, please use the route for emissary
