define: &uid 1000 # For openshift, pls use the UID within the project UID range.
define: &storageclass "" # pls update according to the storageclass provision in your deployment.

rootUser: root 
rootPassword: RootTempPassword1234 # Replace in prod
replicas: 1
mode: standalone

users:
  - accessKey: ai-appstore
    secretKey: TempPassword1234 # Replace in prod
    policy: readwrite
svcaccts:
  - accessKey: aas-minio-uploader
    secretKey: TempPassword1234 # Replace in prod
    user: ai-appstore

buckets:
  - name: model-zoo
    policy: download

persistence:
  size: 10Gi
  storageClass: *storageclass
  accessMode: ReadWriteOnce
  size: 5Gi

resources:
  requests:
    memory: 512Mi

securityContext:
  enabled: true
  runAsUser: *uid
  runAsGroup: *uid
  fsGroup: *uid