define: &uid 1001 # For openshift, pls use the UID within the project UID range.
define: &storageclass "" # pls update according to the storageclass provision in your deployment.

auth:
  enabled: true
  rootUser: aasRootDBUser
  rootPassword: RootTempPassword1234 # NOTE: Replace in production
  usernames:
    - aas-backend-serviceAcct
  passwords: 
    - TempPassword1234 # NOTE: Replace in production
  databases:  
    - appStoreProdDB

persistence:
  enabled: true
  storageClass: *storageclass
  accessModes:
    - ReadWriteOnce
  size: 8Gi

podSecurityContext:
  enabled: true
  fsGroup: *uid

containerSecurityContext:
  enabled: true
  runAsUser: *uid
  runAsNonRoot: true
