schema_version: 2
metadata:
  name: Stable Diffusion
  version: v1
  description: Example user inference engine
  author: Tien Cheng
endpoints:
  predict:
    type: POST
    input_schema: TextIO
    output_schema: MediaFileIO
