{{ if .Values.tags.knativeBackend }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ .Values.inferenceEngineNamespace }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
{{ end }}
