apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: v1
kind: Namespace
metadata:
  name: ai-appstore
  labels:
    webhooks.knative.dev/exclude: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference-engine
