apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: inference-engine-manager
rules:
- apiGroups: ["serving.knative.dev"]
  #
  resources: ["services"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: manage-inference-engine
  namespace: inference-engine
subjects:
- kind: ServiceAccount
  name: backend-service # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: inference-engine-manager
  apiGroup: rbac.authorization.k8s.io
