services:
  inference:
    container_name: cv_inference
    build:
      context: "./inference"
    ports:
      - "5001:5001"
    networks:
      - appstore
  visualization:
    container_name: cv_visualize
    build:
      context: "./visualization"
    ports:
      - "5002:5002"
    networks:
      - appstore
networks:
  appstore:
    external: true
    name: appstore
