name: Back End CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./back-end
    env:
      ENV_STATE: test
      MONGODB_URL: localhost:27017
      MAIN_COLLECTION_NAME: app_store_ci
      MAX_UPLOAD_SIZE_GB: 10
      CLEARML_CONFIG_FILE: tests/test_clearml.conf
      CLEARML_NO_DEFAULT_SERVER: 0
      CLEARML_API_HOST: https://demoapi.trains.allegro.ai/
      CLEARML_WEB_HOST: https://demoapp.trains.allegro.ai/
      CLEARML_FILES_HOST: https://demofiles.trains.allegro.ai/
      CLEARML_API_ACCESS_KEY: ROBE8ZJIDGA1BS126MO8
      CLEARML_API_SECRET_KEY: efXa3I1LRnDBCQra7AeaEvv19oJjTozigz90Rtm7upecb5YUOe
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          # cache: poetry
      - run: |
          poetry install
      - name: Set up environment file
        run: |
          poetry run python scripts/generate-ci-env.py
      - name: Test with pytest
        run: |
          poetry run pytest
