name: Back End CI

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./back-end
    env:
      ENV_STATE: test
      MONGODB_URL: localhost:27017
      MAIN_COLLECTION_NAME: app_store_ci
      MAX_UPLOAD_SIZE_GB: 10
      CLEARML_OFFLINE_MODE: true
    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_DATABASE: app_store_ci
        options: >-
          --health-cmd mongo
          --health-interval 20s
          --health-timeout 5s
          --health-retries 6
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: poetry
      - name: Set up dependencies
        run: |
          pip install poetry
          poetry install
      - name: Set up environment file
        run: |
          poetry run python scripts/generate-ci-env.py
      - name: Test with pytest
        run: |
          poetry run pytest
